### ISSUE TITLE
tensorflow version weights file

### ISSUE THREAD

**Issue by xafha** [PeterL1n/BackgroundMattingV2-TensorFlow#2]
Hi， how to download the tensorflow version weights file？

https://drive.google.com/drive/folders/1cbetlrKREitIgjnIikG1HdM4x72FtgBh
Only Support onnx、torch、torchscripts weights file.
Thanks

**Comment by xafha** [comment]
> Hi， how to download the tensorflow version weights file？
> 
> https://drive.google.com/drive/folders/1cbetlrKREitIgjnIikG1HdM4x72FtgBh
> Only Support onnx、torch、torchscripts weights file.
> Thanks

That's it, I know.

**Comment by PeterL1n** [comment]
TensorFlow uses PyTorch weights. Download the PyTorch weights, then load it into the TensorFlow model through `load_torch_weights` function. Read the example in `README.md`.
